name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: latest
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-audit
        version: latest
    - name: Code coverage
      run: cargo tarpaulin --ignore-tests
    - name: Code linting
      run: cargo clippy
    - name: Code formatting
      run: cargo fmt -- --check
    - name: Code audit
      run: cargo audit
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
